language: python

python:
  - 3.9

install:
  - pip install -r requirements.txt

script:
  - black --check .
  - flake8 .
  - coverage run --source=swe1_app3,polls manage.py test

after_script:
  - coveralls
