language: python

python:
  - 3.8

install:
  - pip install -r requirements.txt
  - pip install black
  - pip install coverage
  - pip install coveralls
  - pip install flake8

before_script:
  - python manage.py migrate
  - python manage.py collectstatic --noinput
  - black .
  
script:
  - black --check .
  - flake8 .
  - coverage run --source=swe1_app3,polls manage.py test

after_script:
  - coveralls

deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: $ACCESS_KEY
  secret_access_key:
    secure: $SECRET_KEY
  region: $REGION
  app: $APP_NAME
  env: $ENV
  bucket_name: $BUCKET_NAME
  on:
    repo: Zhiyuan-Wei/swe1-app3
    branch: main
